import Head from "next/head";
import styles from "../styles/Home.module.css";
import Link from "next/link";
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main} style={{ gap: "50px" }}>
        <h1>MAİN</h1>
        <Link href="/login">
          <a className={styles.link}>Login</a>
        </Link>
        <Link href="/register">
          <a className={styles.link}>Register</a>
        </Link>
      </main>

      <footer className={styles.footer}>FOOTER</footer>
    </div>
  );
}
